# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

homekit:
  advertise_ip: !secret host_ip_address
  port: 21063
  filter:
    include_domains:
      - light
      - cover

google_assistant:
  project_id: !secret google_assistant_project_id
  service_account:
    private_key: !secret google_assistant_service_account_private_key
    client_email: !secret google_assistant_service_account_client_email
  exposed_domains:
    - switch
    - light
    - cover
  report_state: true

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 172.16.0.0/12
    - ::1

hacs:
  token: !secret github_token

automower:
  username: !secret husqvarna_username
  password: !secret husqvarna_password

homeassistant:
  customize: !include customize.yaml

sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
