esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  use_address: ${assigned_ip_address}

  ap:
    ssid: ${friendly_name}
    password: !secret wifi_fallback_password

captive_portal:

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: device/${device_name}

ota:

logger:
  level: WARN

sensor:
  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal
    update_interval: 60s

binary_sensor:
  - platform: gpio
    id: _button
    pin:
      number: GPIO13
      inverted: True
    on_press:
      then:
        - light.toggle: _light

output:
  - platform: gpio
    pin: GPIO12
    id: _relay
  - platform: gpio
    pin: GPIO4
    id: _led
    inverted: True

light:
  - platform: binary
    id: _light
    name: ${friendly_name}
    output: _relay
    on_turn_on:
      - output.turn_off: _led
    on_turn_off:
      - output.turn_on: _led
