esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  use_address: ${assigned_ip_address}

  ap:
    ssid: ${friendly_name}
    password: !secret wifi_fallback_password

captive_portal:

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: device/${device_name}

ota:

logger:
  baud_rate: 0
  level: WARN

sensor:
  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal
    update_interval: 60s
  - platform: template
    name: ${room_friendly_name} Temperature
    device_class: temperature
    lambda: return id(heat_pump).current_temperature;
    update_interval: 15s
    # filters:
    #   - lambda: return x * (9.0/5.0) + 32.0;
    unit_of_measurement: "°C"

external_components:
  - source: github://geoffdavis/esphome-mitsubishiheatpump

climate:
  - platform: mitsubishi_heatpump
    id: heat_pump
    name: ${friendly_name}
    hardware_uart: UART0
    visual:
      min_temperature: 10
