substitutions:
  device_name: foyer-light
  friendly_name: Foyer Light
  assigned_ip_address: "192.168.86.212"

packages:
  dimmer_switch: !include common/dimmer_switch.yaml

mqtt: # needed due to esphome/issues#1487
  broker: !secret mqtt_host
