substitutions:
  device_name: guest-bedroom-light
  friendly_name: Guest Bedroom Light
  assigned_ip_address: "192.168.86.205"

packages:
  dimmer_switch: !include common/dimmer_switch.yaml

mqtt: # needed due to esphome/issues#1487
  broker: !secret mqtt_host
