substitutions:
  device_name: hallway-light
  friendly_name: Hallway Light
  assigned_ip_address: "192.168.86.211"

packages:
  dimmer_switch: !include common/dimmer_switch.yaml

mqtt: # needed due to esphome/issues#1487
  broker: !secret mqtt_host
