substitutions:
  device_name: living-room-left-window-light
  friendly_name: Living Room Left Window Light
  assigned_ip_address: "192.168.86.214"

packages:
  dimmer_switch: !include common/dimmer_switch.yaml

mqtt: # needed due to esphome/issues#1487
  broker: !secret mqtt_host
