substitutions:
  device_name: radiant-heaters
  friendly_name: Radiant Heaters
  assigned_ip_address: "192.168.86.210"
  zone_one_device_name: radiant-heaters-one
  zone_one_friendly_name: Radiant Heaters Zone One
  zone_two_device_name: radiant-heaters-two

packages:
  generic: !include common/generic.yaml

mqtt: # needed due to esphome/issues#1487
  broker: !secret mqtt_host

switch:
  - platform: gpio
    internal: true
    pin: 4
    id: left_door_relay
  - platform: gpio
    internal: true
    pin: 5
    id: right_door_relay

binary_sensor:
  - id: left_door_sensor
    internal: true
    platform: gpio
    pin:
      number: 15
      mode: INPUT
      inverted: False
    device_class: garage_door
    filters:
      - delayed_on_off: 20ms
  - id: right_door_sensor
    internal: true
    platform: gpio
    pin:
      number: 12
      mode: INPUT
      inverted: False
    device_class: garage_door
    filters:
      - delayed_on_off: 20ms

cover:
  - platform: template
    name: ${left_door_friendly_name}
    device_class: garage
    lambda: |-
      if (id(left_door_sensor).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - if:
          condition:
            lambda: 'return id(left_door_sensor).state == false;'
          then:
            - switch.turn_on: left_door_relay
            - delay: 1s
            - switch.turn_off: left_door_relay
    close_action:
      - if:
          condition:
            lambda: 'return id(left_door_sensor).state == true;'
          then:
            - switch.turn_on: left_door_relay
            - delay: 1s
            - switch.turn_off: left_door_relay
  - platform: template
    name: ${right_door_friendly_name}
    device_class: garage
    lambda: |-
      if (id(right_door_sensor).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - if:
          condition:
            lambda: 'return id(right_door_sensor).state == false;'
          then:
            - switch.turn_on: right_door_relay
            - delay: 1s
            - switch.turn_off: right_door_relay
    close_action:
      - if:
          condition:
            lambda: 'return id(right_door_sensor).state == true;'
          then:
            - switch.turn_on: right_door_relay
            - delay: 1s
            - switch.turn_off: right_door_relay
